version: '3.4'

services:

  instance:
    image: 'nekroze/docker-compose-gen:latest'
    build:
      context: ../
      target: final
    container_name: 'docker-compose-gen'

  tests:
    image: 'nekroze/docker-compose-gen:test'
    build:
      context: ../
      target: test
